// <auto-generated />
namespace Percurrentis.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class reAddTrIdforRental : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reAddTrIdforRental));
        
        string IMigrationMetadata.Id
        {
            get { return "201504200834098_reAddTrIdforRental"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
