// <auto-generated />
namespace Percurrentis.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class oneToMany_ManyToOneTest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(oneToMany_ManyToOneTest));
        
        string IMigrationMetadata.Id
        {
            get { return "201503170918335_oneToMany_ManyToOneTest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
