// <auto-generated />
namespace Percurrentis.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class accommodationsProposalLink : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(accommodationsProposalLink));
        
        string IMigrationMetadata.Id
        {
            get { return "201503190710301_accommodationsProposalLink"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
