// <auto-generated />
namespace Percurrentis.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class MakeIdNullableHopefully1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MakeIdNullableHopefully1));
        
        string IMigrationMetadata.Id
        {
            get { return "201503310613024_MakeIdNullableHopefully1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
