SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
--

SET IDENTITY_INSERT PercurrentisDB.dbo.CountryInformation ON
--
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (1, N'Afghanistan', N'AF ', N' AFG ', N'93')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (2, N'Albania', N'AL ', N' ALB ', N'355')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (3, N'Algeria', N'DZ ', N' DZA ', N'213')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (4, N'American Samoa', N'AS ', N' ASM ', N'1 684 ')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (5, N'Andorra', N'AD ', N' AND ', N'376')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (6, N'Angola', N'AO ', N' AGO ', N'244')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (7, N'Anguilla', N'AI ', N' AIA ', N'1 264 ')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (8, N'Antarctica', N'AQ ', N' ATA ', N'672')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (9, N'Antigua and Barbuda', N'AG ', N' ATG ', N'1 268 ')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (10, N'Argentina', N'AR ', N' ARG ', N'54')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (11, N'Armenia', N'AM ', N' ARM ', N'374')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (12, N'Aruba', N'AW ', N' ABW ', N'297')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (13, N'Australia', N'AU ', N' AUS ', N'61')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (14, N'Austria', N'AT ', N' AUT ', N'43')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (15, N'Azerbaijan', N'AZ ', N' AZE ', N'994')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (16, N'Bahamas', N'BS ', N' BHS ', N'1 242 ')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (17, N'Bahrain', N'BH ', N' BHR ', N'973')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (18, N'Bangladesh', N'BD ', N' BGD ', N'880')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (19, N'Barbados', N'BB ', N' BRB ', N'1 246 ')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (20, N'Belarus', N'BY ', N' BLR ', N'375')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (21, N'Belgium', N'BE ', N' BEL ', N'32')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (22, N'Belize', N'BZ ', N' BLZ ', N'501')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (23, N'Benin', N'BJ ', N' BEN ', N'229')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (24, N'Bermuda', N'BM ', N' BMU ', N'1 441 ')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (25, N'Bhutan', N'BT ', N' BTN ', N'975')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (26, N'Bolivia', N'BO ', N' BOL ', N'591')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (27, N'Bosnia and Herzegovina', N'BA ', N' BIH ', N'387')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (28, N'Botswana', N'BW ', N' BWA ', N'267')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (29, N'Brazil', N'BR ', N' BRA ', N'55')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (30, N'British Indian Ocean Territory', N'IO ', N' IOT ', N' ')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (31, N'British Virgin Islands', N'VG ', N' VGB ', N'1 284 ')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (32, N'Brunei', N'BN ', N' BRN ', N'673')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (33, N'Bulgaria', N'BG ', N' BGR ', N'359')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (34, N'Burkina Faso', N'BF ', N' BFA ', N'226')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (35, N'Burma (Myanmar)', N'MM ', N' MMR ', N'95')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (36, N'Burundi', N'BI ', N' BDI ', N'257')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (37, N'Cambodia', N'KH ', N' KHM ', N'855')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (38, N'Cameroon', N'CM ', N' CMR ', N'237')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (39, N'Canada', N'CA ', N' CAN ', N'1')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (40, N'Cape Verde', N'CV ', N' CPV ', N'238')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (41, N'Cayman Islands', N'KY ', N' CYM ', N'1 345 ')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (42, N'Central African Republic', N'CF ', N' CAF ', N'236')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (43, N'Chad', N'TD ', N' TCD ', N'235')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (44, N'Chile', N'CL ', N' CHL ', N'56')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (45, N'China', N'CN ', N' CHN ', N'86')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (46, N'Christmas Island', N'CX ', N' CXR ', N'61')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (47, N'Cocos (Keeling) Islands', N'CC ', N' CCK ', N'61')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (48, N'Colombia', N'CO ', N' COL ', N'57')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (49, N'Comoros', N'KM ', N' COM ', N'269')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (50, N'Cook Islands', N'CK ', N' COK ', N'682')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (51, N'Costa Rica', N'CR ', N' CRC ', N'506')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (52, N'Croatia', N'HR ', N' HRV ', N'385')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (53, N'Cuba', N'CU ', N' CUB ', N'53')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (54, N'Cyprus', N'CY ', N' CYP ', N'357')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (55, N'Czech Republic', N'CZ ', N' CZE ', N'420')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (56, N'Democratic Republic of the Congo', N'CD ', N' COD ', N'243')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (57, N'Denmark', N'DK ', N' DNK ', N'45')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (58, N'Djibouti', N'DJ ', N' DJI ', N'253')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (59, N'Dominica', N'DM ', N' DMA ', N'1 767 ')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (60, N'Dominican Republic', N'DO ', N' DOM ', N'1 809 ')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (61, N'Ecuador', N'EC ', N' ECU ', N'593')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (62, N'Egypt', N'EG ', N' EGY ', N'20')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (63, N'El Salvador', N'SV ', N' SLV ', N'503')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (64, N'Equatorial Guinea', N'GQ ', N' GNQ ', N'240')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (65, N'Eritrea', N'ER ', N' ERI ', N'291')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (66, N'Estonia', N'EE ', N' EST ', N'372')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (67, N'Ethiopia', N'ET ', N' ETH ', N'251')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (68, N'Falkland Islands', N'FK ', N' FLK ', N'500')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (69, N'Faroe Islands', N'FO ', N' FRO ', N'298')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (70, N'Fiji', N'FJ ', N' FJI ', N'679')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (71, N'Finland', N'FI ', N' FIN ', N'358')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (72, N'France', N'FR ', N' FRA ', N'33')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (73, N'French Polynesia', N'PF ', N' PYF ', N'689')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (74, N'Gabon', N'GA ', N' GAB ', N'241')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (75, N'Gambia', N'GM ', N' GMB ', N'220')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (76, N'Gaza Strip', N' ', N' ', N'970')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (77, N'Georgia', N'GE ', N' GEO ', N'995')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (78, N'Germany', N'DE ', N' DEU ', N'49')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (79, N'Ghana', N'GH ', N' GHA ', N'233')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (80, N'Gibraltar', N'GI ', N' GIB ', N'350')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (81, N'Greece', N'GR ', N' GRC ', N'30')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (82, N'Greenland', N'GL ', N' GRL ', N'299')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (83, N'Grenada', N'GD ', N' GRD ', N'1 473 ')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (84, N'Guam', N'GU ', N' GUM ', N'1 671 ')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (85, N'Guatemala', N'GT ', N' GTM ', N'502')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (86, N'Guinea', N'GN ', N' GIN ', N'224')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (87, N'Guinea-Bissau', N'GW ', N' GNB ', N'245')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (88, N'Guyana', N'GY ', N' GUY ', N'592')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (89, N'Haiti', N'HT ', N' HTI ', N'509')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (90, N'Holy See (Vatican City)', N'VA ', N' VAT ', N'39')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (91, N'Honduras', N'HN ', N' HND ', N'504')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (92, N'Hong Kong', N'HK ', N' HKG ', N'852')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (93, N'Hungary', N'HU ', N' HUN ', N'36')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (94, N'Iceland', N'IS ', N' IS ', N'354')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (95, N'India', N'IN ', N' IND ', N'91')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (96, N'Indonesia', N'ID ', N' IDN ', N'62')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (97, N'Iran', N'IR ', N' IRN ', N'98')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (98, N'Iraq', N'IQ ', N' IRQ ', N'964')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (99, N'Ireland', N'IE ', N' IRL ', N'353')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (100, N'Isle of Man', N'IM ', N' IMN ', N'44')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (101, N'Israel', N'IL ', N' ISR ', N'972')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (102, N'Italy', N'IT ', N' ITA ', N'39')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (103, N'Ivory Coast', N'CI ', N' CIV ', N'225')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (104, N'Jamaica', N'JM ', N' JAM ', N'1 876 ')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (105, N'Japan', N'JP ', N' JPN ', N'81')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (106, N'Jersey', N'JE ', N' JEY ', N' ')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (107, N'Jordan', N'JO ', N' JOR ', N'962')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (108, N'Kazakhstan', N'KZ ', N' KAZ ', N'7')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (109, N'Kenya', N'KE ', N' KEN ', N'254')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (110, N'Kiribati', N'KI ', N' KIR ', N'686')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (111, N'Kosovo', N' ', N' ', N'381')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (112, N'Kuwait', N'KW ', N' KWT ', N'965')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (113, N'Kyrgyzstan', N'KG ', N' KGZ ', N'996')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (114, N'Laos', N'LA ', N' LAO ', N'856')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (115, N'Latvia', N'LV ', N' LVA ', N'371')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (116, N'Lebanon', N'LB ', N' LBN ', N'961')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (117, N'Lesotho', N'LS ', N' LSO ', N'266')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (118, N'Liberia', N'LR ', N' LBR ', N'231')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (119, N'Libya', N'LY ', N' LBY ', N'218')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (120, N'Liechtenstein', N'LI ', N' LIE ', N'423')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (121, N'Lithuania', N'LT ', N' LTU ', N'370')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (122, N'Luxembourg', N'LU ', N' LUX ', N'352')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (123, N'Macau', N'MO ', N' MAC ', N'853')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (124, N'Macedonia', N'MK ', N' MKD ', N'389')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (125, N'Madagascar', N'MG ', N' MDG ', N'261')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (126, N'Malawi', N'MW ', N' MWI ', N'265')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (127, N'Malaysia', N'MY ', N' MYS ', N'60')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (128, N'Maldives', N'MV ', N' MDV ', N'960')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (129, N'Mali', N'ML ', N' MLI ', N'223')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (130, N'Malta', N'MT ', N' MLT ', N'356')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (131, N'Marshall Islands', N'MH ', N' MHL ', N'692')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (132, N'Mauritania', N'MR ', N' MRT ', N'222')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (133, N'Mauritius', N'MU ', N' MUS ', N'230')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (134, N'Mayotte', N'YT ', N' MYT ', N'262')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (135, N'Mexico', N'MX ', N' MEX ', N'52')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (136, N'Micronesia', N'FM ', N' FSM ', N'691')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (137, N'Moldova', N'MD ', N' MDA ', N'373')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (138, N'Monaco', N'MC ', N' MCO ', N'377')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (139, N'Mongolia', N'MN ', N' MNG ', N'976')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (140, N'Montenegro', N'ME ', N' MNE ', N'382')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (141, N'Montserrat', N'MS ', N' MSR ', N'1 664 ')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (142, N'Morocco', N'MA ', N' MAR ', N'212')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (143, N'Mozambique', N'MZ ', N' MOZ ', N'258')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (144, N'Namibia', N'NA ', N' NAM ', N'264')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (145, N'Nauru', N'NR ', N' NRU ', N'674')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (146, N'Nepal', N'NP ', N' NPL ', N'977')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (147, N'Netherlands', N'NL ', N' NLD ', N'31')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (148, N'Netherlands Antilles', N'AN ', N' ANT ', N'599')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (149, N'New Caledonia', N'NC ', N' NCL ', N'687')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (150, N'New Zealand', N'NZ ', N' NZL ', N'64')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (151, N'Nicaragua', N'NI ', N' NIC ', N'505')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (152, N'Niger', N'NE ', N' NER ', N'227')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (153, N'Nigeria', N'NG ', N' NGA ', N'234')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (154, N'Niue', N'NU ', N' NIU ', N'683')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (155, N'Norfolk Island', N' ', N' NFK ', N'672')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (156, N'North Korea', N'KP ', N' PRK ', N'850')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (157, N'Northern Mariana Islands', N'MP ', N' MNP ', N'1 670 ')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (158, N'Norway', N'NO ', N' NOR ', N'47')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (159, N'Oman', N'OM ', N' OMN ', N'968')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (160, N'Pakistan', N'PK ', N' PAK ', N'92')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (161, N'Palau', N'PW ', N' PLW ', N'680')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (162, N'Panama', N'PA ', N' PAN ', N'507')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (163, N'Papua New Guinea', N'PG ', N' PNG ', N'675')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (164, N'Paraguay', N'PY ', N' PRY ', N'595')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (165, N'Peru', N'PE ', N' PER ', N'51')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (166, N'Philippines', N'PH ', N' PHL ', N'63')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (167, N'Pitcairn Islands', N'PN ', N' PCN ', N'870')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (168, N'Poland', N'PL ', N' POL ', N'48')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (169, N'Portugal', N'PT ', N' PRT ', N'351')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (170, N'Puerto Rico', N'PR ', N' PRI ', N'1')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (171, N'Qatar', N'QA ', N' QAT ', N'974')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (172, N'Republic of the Congo', N'CG ', N' COG ', N'242')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (173, N'Romania', N'RO ', N' ROU ', N'40')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (174, N'Russia', N'RU ', N' RUS ', N'7')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (175, N'Rwanda', N'RW ', N' RWA ', N'250')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (176, N'Saint Barthelemy', N'BL ', N' BLM ', N'590')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (177, N'Saint Helena', N'SH ', N' SHN ', N'290')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (178, N'Saint Kitts and Nevis', N'KN ', N' KNA ', N'1 869 ')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (179, N'Saint Lucia', N'LC ', N' LCA ', N'1 758 ')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (180, N'Saint Martin', N'MF ', N' MAF ', N'1 599 ')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (181, N'Saint Pierre and Miquelon', N'PM ', N' SPM ', N'508')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (182, N'Saint Vincent and the Grenadines', N'VC ', N' VCT ', N'1 784 ')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (183, N'Samoa', N'WS ', N' WSM ', N'685')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (184, N'San Marino', N'SM ', N' SMR ', N'378')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (185, N'Sao Tome and Principe', N'ST ', N' STP ', N'239')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (186, N'Saudi Arabia', N'SA ', N' SAU ', N'966')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (187, N'Senegal', N'SN ', N' SEN ', N'221')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (188, N'Serbia', N'RS ', N' SRB ', N'381')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (189, N'Seychelles', N'SC ', N' SYC ', N'248')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (190, N'Sierra Leone', N'SL ', N' SLE ', N'232')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (191, N'Singapore', N'SG ', N' SGP ', N'65')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (192, N'Slovakia', N'SK ', N' SVK ', N'421')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (193, N'Slovenia', N'SI ', N' SVN ', N'386')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (194, N'Solomon Islands', N'SB ', N' SLB ', N'677')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (195, N'Somalia', N'SO ', N' SOM ', N'252')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (196, N'South Africa', N'ZA ', N' ZAF ', N'27')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (197, N'South Korea', N'KR ', N' KOR ', N'82')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (198, N'Spain', N'ES ', N' ESP ', N'34')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (199, N'Sri Lanka', N'LK ', N' LKA ', N'94')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (200, N'Sudan', N'SD ', N' SDN ', N'249')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (201, N'Suriname', N'SR ', N' SUR ', N'597')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (202, N'Svalbard', N'SJ ', N' SJM ', N' ')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (203, N'Swaziland', N'SZ ', N' SWZ ', N'268')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (204, N'Sweden', N'SE ', N' SWE ', N'46')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (205, N'Switzerland', N'CH ', N' CHE ', N'41')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (206, N'Syria', N'SY ', N' SYR ', N'963')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (207, N'Taiwan', N'TW ', N' TWN ', N'886')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (208, N'Tajikistan', N'TJ ', N' TJK ', N'992')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (209, N'Tanzania', N'TZ ', N' TZA ', N'255')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (210, N'Thailand', N'TH ', N' THA ', N'66')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (211, N'Timor-Leste', N'TL ', N' TLS ', N'670')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (212, N'Togo', N'TG ', N' TGO ', N'228')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (213, N'Tokelau', N'TK ', N' TKL ', N'690')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (214, N'Tonga', N'TO ', N' TON ', N'676')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (215, N'Trinidad and Tobago', N'TT ', N' TTO ', N'1 868 ')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (216, N'Tunisia', N'TN ', N' TUN ', N'216')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (217, N'Turkey', N'TR ', N' TUR ', N'90')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (218, N'Turkmenistan', N'TM ', N' TKM ', N'993')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (219, N'Turks and Caicos Islands', N'TC ', N' TCA ', N'1 649 ')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (220, N'Tuvalu', N'TV ', N' TUV ', N'688')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (221, N'Uganda', N'UG ', N' UGA ', N'256')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (222, N'Ukraine', N'UA ', N' UKR ', N'380')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (223, N'United Arab Emirates', N'AE ', N' ARE ', N'971')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (224, N'United Kingdom', N'GB ', N' GBR ', N'44')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (225, N'United States', N'US ', N' USA ', N'1')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (226, N'Uruguay', N'UY ', N' URY ', N'598')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (227, N'US Virgin Islands', N'VI ', N' VIR ', N'1 340 ')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (228, N'Uzbekistan', N'UZ ', N' UZB ', N'998')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (229, N'Vanuatu', N'VU ', N' VUT ', N'678')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (230, N'Venezuela', N'VE ', N' VEN ', N'58')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (231, N'Vietnam', N'VN ', N' VNM ', N'84')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (232, N'Wallis and Futuna', N'WF ', N' WLF ', N'681')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (233, N'West Bank', N' ', N' ', N'970')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (234, N'Western Sahara', N'EH ', N' ESH ', N' ')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (235, N'Yemen', N'YE ', N' YEM ', N'967')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (236, N'Zambia', N'ZM ', N' ZMB ', N'260')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (237, N'Zimbabwe', N'ZW ', N' ZWE ', N'263')
INSERT PercurrentisDB.dbo.CountryInformation(Id, Name, CountryCode, ISO, CallCode) VALUES (238, N'Not Selected', N'XX ', N' XXX ', N'XXX')
--
SET IDENTITY_INSERT PercurrentisDB.dbo.CountryInformation OFF
--