SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
--

SET IDENTITY_INSERT PercurrentisDB.dbo.Currency ON
--
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('1','United Arab Emirates dirham','AED');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('2','Afghani','AFN');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('3','Lek','ALL');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('4','Armenian Dram','AMD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('5','Netherlands Antillian Guilder','ANG');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('6','Kwanza','AOA');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('7','Argentine Peso','ARS');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('8','Australian Dollar','AUD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('9','Aruban Guilder','AWG');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('10','Azerbaijanian Manat','AZN');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('11','Convertible Marks','BAM');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('12','Barbados Dollar','BBD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('13','Bangladeshi Taka','BDT');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('14','Bulgarian Lev','BGN');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('15','Bahraini Dinar','BHD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('16','Burundian Franc','BIF');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('17','Bermudian Dollar','BMD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('18','Brunei Dollar','BND');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('19','Boliviano','BOB');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('20','Bolivian Mvdol','BOV');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('21','Brazilian Real','BRL');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('22','Bahamian Dollar','BSD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('23','Ngultrum','BTN');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('24','Pula','BWP');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('25','Belarussian Ruble','BYR');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('26','Belize Dollar','BZD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('27','Canadian Dollar','CAD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('28','Franc Congolais','CDF');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('29','WIR Euro','CHE');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('30','Swiss Franc','CHF');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('31','Chilean Peso','CLP');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('32','Yuan Renminbi','CNY');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('33','Colombian Peso','COP');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('34','Unidad de Valor Real','COU');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('35','Costa Rican Colon','CRC');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('36','Cuban Peso','CUP');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('37','Cape Verde Escudo','CVE');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('38','Cyprus Pound','CYP');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('39','Czech Koruna','CZK');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('40','Djibouti Franc','DJF');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('41','Danish Krone','DKK');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('42','Dominican Peso','DOP');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('43','Algerian Dinar','DZD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('44','Kroon','EEK');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('45','Egyptian Pound','EGP');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('46','Nakfa','ERN');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('47','Ethiopian Birr','ETB');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('49','Fiji Dollar','FJD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('50','Falkland Islands Pound','FKP');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('51','Pound Sterling','GBP');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('52','Lari','GEL');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('53','Cedi','GHS');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('54','Gibraltar pound','GIP');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('55','Dalasi','GMD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('56','Guinea Franc','GNF');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('57','Quetzal','GTQ');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('58','Guyana Dollar','GYD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('59','Hong Kong Dollar','HKD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('60','Lempira','HNL');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('61','Croatian Kuna','HRK');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('62','Haiti Gourde','HTG');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('63','Forint','HUF');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('64','Rupiah','IDR');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('65','New Israeli Shekel','ILS');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('66','Indian Rupee','INR');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('67','Iraqi Dinar','IQD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('68','Iranian Rial','IRR');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('69','Iceland Krona','ISK');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('70','Jamaican Dollar','JMD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('71','Jordanian Dinar','JOD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('72','Japanese yen','JPY');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('73','Kenyan Shilling','KES');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('74','Som','KGS');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('75','Riel','KHR');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('76','Comoro Franc','KMF');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('77','North Korean Won','KPW');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('78','South Korean Won','KRW');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('79','Kuwaiti Dinar','KWD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('80','Cayman Islands Dollar','KYD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('81','Tenge','KZT');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('82','Kip','LAK');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('83','Lebanese Pound','LBP');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('84','Sri Lanka Rupee','LKR');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('85','Liberian Dollar','LRD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('86','Loti','LSL');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('87','Lithuanian Litas','LTL');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('88','Latvian Lats','LVL');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('89','Libyan Dinar','LYD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('90','Moroccan Dirham','MAD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('91','Moldovan Leu','MDL');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('92','Malagasy Ariary','MGA');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('93','Denar','MKD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('94','Kyat','MMK');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('95','Tugrik','MNT');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('96','Pataca','MOP');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('97','Ouguiya','MRO');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('98','Maltese Lira','MTL');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('99','Mauritius Rupee','MUR');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('100','Rufiyaa','MVR');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('101','Kwacha','MWK');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('102','Mexican Peso','MXN');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('103','Malaysian Ringgit','MYR');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('104','Metical','MZN');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('105','Namibian Dollar','NAD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('106','Naira','NGN');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('107','Cordoba Oro','NIO');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('108','Norwegian Krone','NOK');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('109','Nepalese Rupee','NPR');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('110','New Zealand Dollar','NZD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('111','Rial Omani','OMR');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('112','Balboa','PAB');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('113','Nuevo Sol','PEN');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('114','Kina','PGK');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('115','Philippine Peso','PHP');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('116','Pakistan Rupee','PKR');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('117','Zloty','PLN');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('118','Guarani','PYG');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('119','Qatari Rial','QAR');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('120','Romanian New Leu','RON');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('121','Serbian Dinar','RSD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('122','Russian Ruble','RUB');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('123','Rwanda Franc','RWF');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('124','Saudi Riyal','SAR');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('125','Solomon Islands Dollar','SBD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('126','Seychelles Rupee','SCR');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('127','Sudanese Pound','SDG');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('128','Swedish Krona','SEK');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('129','Singapore Dollar','SGD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('130','Saint Helena Pound','SHP');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('131','Slovak Koruna','SKK');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('132','Leone','SLL');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('133','Somali Shilling','SOS');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('134','Surinam Dollar','SRD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('135','Dobra','STD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('136','Syrian Pound','SYP');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('137','Lilangeni','SZL');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('138','Baht','THB');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('139','Somoni','TJS');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('140','Manat','TMM');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('141','Tunisian Dinar','TND');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('142','New Turkish Lira','TRY');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('143','Trinidad and Tobago Dollar','TTD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('144','New Taiwan Dollar','TWD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('145','Tanzanian Shilling','TZS');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('146','Hryvnia','UAH');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('147','Uganda Shilling','UGX');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('148','US Dollar','USD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('149','Peso Uruguayo','UYU');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('150','Uzbekistan Som','UZS');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('151','Venezuelan bolívar','VEB');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('152','Vietnamese đồng','VND');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('153','Vatu','VUV');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('154','Samoan Tala','WST');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('155','CFA Franc BEAC','XAF');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('156','East Caribbean Dollar','XCD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('157','CFA Franc BCEAO','XOF');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('158','CFP franc','XPF');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('159','Yemeni Rial','YER');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('160','South African Rand','ZAR');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('161','Kwacha','ZMK');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('162','Zimbabwe Dollar','ZWD');
INSERT INTO Currency (Id,Name,CurrencyCode) VALUES ('163','Chinese Yuan Renminbi','CNY');


--
SET IDENTITY_INSERT PercurrentisDB.dbo.Currency OFF
--